### Show quantile estimation with SGD  "works"

1. Test datasets:
    - Mixsture of 5 Gaussians
    - Sample of 100k from no.1
    - Gausian $\mu = 2, \sigma = 18$
    - Gausian $\mu = 0, \sigma = 0.001$
    - Sample 100 from no.1
    - Sample 100 from no.3
    - Exponential $\lambda$
    - My weird distribution lol
    
4. Test times:
    - 10 $\times$ dataset generation
    - 10 $\times$ SGD ???
    - 10 $\times$ shuffle (does the order matter?)
    
2. Q value: 0.1, 0.3, 0.5, 0.9, 0.99 

3. Step size: 
    - $\alpha_k = 1$
    - $\alpha_k = \frac{2}{\sqrt{k}}$
    - $\alpha_k = \frac{0.002}{\sqrt{k}}$
    - ?
    - ?
    - Why's the Newton method helpful?
       
5. Calculate $E = |q_{batch} - q_{sgd}|$

6. What's a small value of $E$?

7. Investigate the effect of datasize N
    - Convergence rate with same $\alpha_k$?
    - Different Q values?
    - ?

In [4]:
%matplotlib inline
import numpy as np

In [23]:
q_values = [0.1, 0.3, 0.5, 0.9, 0.99]
N_generation = 12
N_shuffle = 10

a = np.zeros((N_shuffle, len(q_values)))
a.shape

(10, 5)

In [42]:
def generate_dataset(distro, data_size):
    return np.random.normal(0, 0.1, (3,4))

# generate_dataset(True, True)

array([[-0.07310707,  0.22070778, -0.28509463, -0.05076965],
       [ 0.04423327, -0.1456886 , -0.10179877,  0.11275124],
       [ 0.00741648,  0.2047395 , -0.08450196,  0.13094117]])

In [37]:
def generate_q_batch(dataset):
    return np.random.normal(0, 1, len(q_values))

In [38]:
def generate_q_sgd(dataset, step_size):
    return np.random.uniform(0, 2, len(q_values))

In [40]:
def draw_image(q_batches, q_sgds):
#     draw only one line of q_batches, and one block of q_sgds
    
    return None

In [41]:
def compare_distributions(distro, data_size, step_size):
    q_batches = np.zeros((N_generation, len(q_values)))
    q_sgds = np.zeros((N_generation, N_shuffle, len(q_values)))
    
    # generate datasets
    for i in range(N_generation):
        dataset = generate_dataset(distro, data_size)
        q_batch = generate_q_batch(dataset)
        q_batches[i] = q_batch

        # shuffle
        for j in range(10):
            np.random.shuffle(dataset)
            q_sgd   = generate_q_sgd(dataset, step_size)
            q_sgds[i][j] = q_sgd
    draw_image(q_batches, q_sgds)
    print (q_batches)
    return

compare_distributions(True, True, False)

[[ 1.48610098 -0.30914006  0.14728036  0.00489237  0.6508779 ]
 [-2.61064461 -0.14748842  0.48328977 -0.1663612  -0.48547244]
 [ 0.82003433 -0.01219056  0.17217907  0.04371225  1.51591731]
 [ 0.59556583  0.89956096 -0.30135147  1.40234715 -2.60350481]
 [-0.1644905   0.37664169  0.35426881  0.98946032 -0.14422581]
 [ 0.12407755  1.41173678  1.35196179 -0.02500737  2.1128174 ]
 [-1.02117003 -0.35665341 -1.19453555  1.10170299 -0.59891911]
 [-0.24803351 -0.15288007  0.38784422  1.35151766  1.30128051]
 [ 0.03589115 -1.06944515  0.14869823 -2.21242658 -0.29021889]
 [-0.38623941 -1.09637832 -0.7585291  -0.32613705  0.57108458]
 [ 0.0764211   1.83340927  1.49653299  0.33621157  1.27374164]
 [-1.14752644  0.63529581  1.21931406 -0.81587116  0.4765054 ]]


In [11]:
def compare_step_sizes(step_size, distro, data_size):
    return

In [12]:
def compare_data_size(data_size, distro, setp_size):
    return